version: 0.1

# The region to create the synthetic demand for
region: World

# Definition for the regions
regions:
    # Full list for GADM0 world taken from GEGIS
    World:
        - Afghanistan
        - Akrotiri and Dhekelia
        - Albania
        - Algeria
        - American Samoa
        - Andorra
        - Angola
        - Anguilla
        # Does not work with GEGIS
        # - Antarctica
        - Antigua and Barbuda
        - Argentina
        - Armenia
        - Aruba
        - Australia
        - Austria
        - Azerbaijan
        - Bahamas
        - Bahrain
        - Bangladesh
        - Barbados
        - Belarus
        - Belgium
        - Belize
        - Benin
        - Bermuda
        - Bhutan
        - Bolivia
        - Bonaire, Sint Eustatius and Saba
        - Bosnia and Herzegovina
        - Botswana
        - Bouvet Island
        - Brazil
        - British Indian Ocean Territory
        - British Virgin Islands
        - Brunei
        - Bulgaria
        - Burkina Faso
        - Burundi
        - Cambodia
        - Cameroon
        - Canada
        - Cape Verde
        # Does not work with GEGIS
        # - Caspian Sea
        - Cayman Islands
        - Central African Republic
        - Chad
        - Chile
        - China
        - Christmas Island
        - Clipperton Island
        - Cocos Islands
        - Colombia
        - Comoros
        - Cook Islands
        - Costa Rica
        - Croatia
        - Cuba
        - Curaçao
        - Cyprus
        - Czech Republic
        - Côte d'Ivoire
        - Democratic Republic of the Congo
        - Denmark
        - Djibouti
        - Dominica
        - Dominican Republic
        - Ecuador
        - Egypt
        - El Salvador
        - Equatorial Guinea
        - Eritrea
        - Estonia
        - Ethiopia
        - Falkland Islands
        - Faroe Islands
        - Fiji
        - Finland
        - France
        - French Guiana
        - French Polynesia
        - French Southern Territories
        - Gabon
        - Gambia
        - Georgia
        - Germany
        - Ghana
        - Gibraltar
        - Greece
        - Greenland
        - Grenada
        - Guadeloupe
        - Guam
        - Guatemala
        - Guernsey
        - Guinea
        - Guinea-Bissau
        - Guyana
        - Haiti
        - Heard Island and McDonald Islands
        - Honduras
        - Hong Kong
        - Hungary
        - Iceland
        - India
        - Indonesia
        - Iran
        - Iraq
        - Ireland
        - Isle of Man
        - Israel
        - Italy
        - Jamaica
        - Japan
        - Jersey
        - Jordan
        - Kazakhstan
        - Kenya
        - Kiribati
        - Kosovo
        - Kuwait
        - Kyrgyzstan
        - Laos
        - Latvia
        - Lebanon
        - Lesotho
        - Liberia
        - Libya
        - Liechtenstein
        - Lithuania
        - Luxembourg
        - Macao
        - Macedonia
        - Madagascar
        - Malawi
        - Malaysia
        - Maldives
        - Mali
        - Malta
        - Marshall Islands
        - Martinique
        - Mauritania
        - Mauritius
        - Mayotte
        - Mexico
        - Micronesia
        - Moldova
        - Monaco
        - Mongolia
        - Montenegro
        - Montserrat
        - Morocco
        - Mozambique
        - Myanmar
        - Namibia
        - Nauru
        - Nepal
        - Netherlands
        - New Caledonia
        - New Zealand
        - Nicaragua
        - Niger
        - Nigeria
        - Niue
        - Norfolk Island
        - North Korea
        - Northern Cyprus
        - Northern Mariana Islands
        - Norway
        - Oman
        - Pakistan
        - Palau
        - Palestina
        - Panama
        - Papua New Guinea
        - Paracel Islands
        - Paraguay
        - Peru
        - Philippines
        - Pitcairn Islands
        - Poland
        - Portugal
        - Puerto Rico
        - Qatar
        - Republic of Congo
        - Reunion
        - Romania
        - Russia
        - Rwanda
        - Saint Helena
        - Saint Kitts and Nevis
        - Saint Lucia
        - Saint Pierre and Miquelon
        - Saint Vincent and the Grenadines
        - Saint-Barthélemy
        - Saint-Martin
        - Samoa
        - San Marino
        - Saudi Arabia
        - Senegal
        - Serbia
        - Seychelles
        - Sierra Leone
        - Singapore
        - Sint Maarten
        - Slovakia
        - Slovenia
        - Solomon Islands
        - Somalia
        - South Africa
        - South Georgia and the South Sandwich Islands
        - South Korea
        - South Sudan
        - Spain
        - Spratly Islands
        - Sri Lanka
        - Sudan
        - Suriname
        - Svalbard and Jan Mayen
        - Swaziland
        - Sweden
        - Switzerland
        - Syria
        - São Tomé and Príncipe
        - Taiwan
        - Tajikistan
        - Tanzania
        - Thailand
        - Timor-Leste
        - Togo
        - Tokelau
        - Tonga
        - Trinidad and Tobago
        - Tunisia
        - Turkey
        - Turkmenistan
        - Turks and Caicos Islands
        - Tuvalu
        - Uganda
        - Ukraine
        - United Arab Emirates
        - United Kingdom
        - United States
        - United States Minor Outlying Islands
        - Uruguay
        - Uzbekistan
        - Vanuatu
        - Vatican City
        - Venezuela
        - Vietnam
        - Virgin Islands, U.S.
        - Wallis and Futuna
        - Western Sahara
        - Yemen
        - Zambia
        - Zimbabwe
        - Åland
