# SPDX-FileCopyrightText: 2021 Johannes Hampp <johannes.hampp@zeu.jlug.de>
#
# SPDX-License-Identifier: CC0-1.0

# Note: This file is separate from the config.yaml file (albeit I would regularly integrate it there)
# The reason is that the config.yaml file is loaded by Snakemake upon execution
# For (a to me unknown reason) the single quote in the country name for "Côte d'Ivoire" breaks
# the internal YAML loading process and Julia scripts.
# Manually loading this file does not break the game, therefore we separate region.yaml and config.yaml .

# Definition for the regions
# Based on GADM0 list for taken from GEGIS (which is v2.8 of GADM database, therefore some country names do not match UN/ISO 3166-2)
# Assignment to continents automatically taken from python package pycountry_convert
regions:
  Africa:
    AO: Angola
    BF: Burkina Faso
    BI: Burundi
    BJ: Benin
    BW: Botswana
    CD: Democratic Republic of the Congo
    CF: Central African Republic
    CG: Republic of Congo
    CI: Côte d'Ivoire
    CM: Cameroon
    CV: Cape Verde
    DJ: Djibouti
    DZ: Algeria
    EG: Egypt
    EH: Western Sahara
    ER: Eritrea
    ET: Ethiopia
    GA: Gabon
    GH: Ghana
    GM: Gambia
    GN: Guinea
    GQ: Equatorial Guinea
    GW: Guinea-Bissau
    KE: Kenya
    KM: Comoros
    LR: Liberia
    LS: Lesotho
    LY: Libya
    MA: Morocco
    MG: Madagascar
    ML: Mali
    MR: Mauritania
    MU: Mauritius
    MW: Malawi
    MZ: Mozambique
    NA: Namibia
    NE: Niger
    NG: Nigeria
    RE: Reunion
    RW: Rwanda
    SC: Seychelles
    SD: Sudan
    SL: Sierra Leone
    SN: Senegal
    SO: Somalia
    SS: South Sudan
    ST: São Tomé and Príncipe
    SZ: Swaziland
    TD: Chad
    TG: Togo
    TN: Tunisia
    TZ: Tanzania
    UG: Uganda
    YT: Mayotte
    ZA: South Africa
    ZM: Zambia
    ZW: Zimbabwe
  Asia:
    AE: United Arab Emirates
    AF: Afghanistan
    AM: Armenia
    AZ: Azerbaijan
    BD: Bangladesh
    BH: Bahrain
    BN: Brunei
    BT: Bhutan
    CN: China
    CY: Cyprus
    GE: Georgia
    HK: Hong Kong
    ID: Indonesia
    IL: Israel
    IN: India
    IQ: Iraq
    IR: Iran
    JO: Jordan
    JP: Japan
    KG: Kyrgyzstan
    KH: Cambodia
    KP: North Korea
    KR: South Korea
    KW: Kuwait
    KZ: Kazakhstan
    LA: Laos
    LB: Lebanon
    LK: Sri Lanka
    MM: Myanmar
    MN: Mongolia
    MV: Maldives
    MY: Malaysia
    NP: Nepal
    OM: Oman
    PH: Philippines
    PK: Pakistan
    PS: Palestina
    QA: Qatar
    SA: Saudi Arabia
    SG: Singapore
    SY: Syria
    TH: Thailand
    TJ: Tajikistan
    TL: Timor-Leste
    TM: Turkmenistan
    TR: Turkey
    TW: Taiwan
    UZ: Uzbekistan
    VN: Vietnam
    YE: Yemen
  Europe:
    AD: Andorra
    AL: Albania
    AT: Austria
    AX: Åland
    BA: Bosnia and Herzegovina
    BE: Belgium
    BG: Bulgaria
    BY: Belarus
    CH: Switzerland
    CZ: Czech Republic
    DE: Germany
    DK: Denmark
    EE: Estonia
    ES: Spain
    FI: Finland
    FO: Faroe Islands
    FR: France
    GB: United Kingdom
    GI: Gibraltar
    GR: Greece
    HR: Croatia
    HU: Hungary
    IE: Ireland
    IM: Isle of Man
    IS: Iceland
    IT: Italy
    LI: Liechtenstein
    LT: Lithuania
    LU: Luxembourg
    LV: Latvia
    MD: Moldova
    ME: Montenegro
    MK: Macedonia
    MT: Malta
    NL: Netherlands
    NO: Norway
    PL: Poland
    PT: Portugal
    RO: Romania
    RS: Serbia
    RU: Russia
    SE: Sweden
    SI: Slovenia
    SK: Slovakia
    SM: San Marino
    UA: Ukraine
    VA: Vatican City
  NorthAmerica:
    AG: Antigua and Barbuda
    BB: Barbados
    BQ: Bonaire, Sint Eustatius and Saba
    BS: Bahamas
    BZ: Belize
    CA: Canada
    CR: Costa Rica
    CU: Cuba
    CW: Curaçao
    DM: Dominica
    DO: Dominican Republic
    GD: Grenada
    GL: Greenland
    GP: Guadeloupe
    GT: Guatemala
    HN: Honduras
    HT: Haiti
    JM: Jamaica
    LC: Saint Lucia
    MQ: Martinique
    MX: Mexico
    NI: Nicaragua
    PA: Panama
    PM: Saint Pierre and Miquelon
    PR: Puerto Rico
    SV: El Salvador
    TC: Turks and Caicos Islands
    TT: Trinidad and Tobago
    US: United States
    VC: Saint Vincent and the Grenadines
  Oceania:
    AU: Australia
    FJ: Fiji
    GU: Guam
    KI: Kiribati
    MP: Northern Mariana Islands
    NC: New Caledonia
    NZ: New Zealand
    PF: French Polynesia
    PG: Papua New Guinea
    PW: Palau
    SB: Solomon Islands
    TO: Tonga
    VU: Vanuatu
    WS: Samoa
  SouthAmerica:
    AR: Argentina
    BO: Bolivia
    BR: Brazil
    CL: Chile
    CO: Colombia
    EC: Ecuador
    FK: Falkland Islands
    GF: French Guiana
    GY: Guyana
    PE: Peru
    PY: Paraguay
    SR: Suriname
    UY: Uruguay
    VE: Venezuela
