# SPDX-FileCopyrightText: 2021 Johannes Hampp <johannes.hampp@zeu.jlug.de>
#
# SPDX-License-Identifier: MIT

[deps]
GlobalEnergyGIS = "31bfc850-377e-11e9-327a-adf9289f3a6c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
